In [2]:
import pandas as pd
df1 = pd.read_csv("princess_corpus.csv")
df = df1.copy()
df.head()

,Disney_Period,Text,Speaker_Status,Movie,Speaker,Year,UTTERANCE_NUMBER
0,EARLY,slave in the magic mirror come from the farthe...,NON-P,Snow White,queen,1937,1
1,EARLY,"what wouldst thou know, my queen ?",NON-P,Snow White,mirror,1937,2
2,EARLY,"magic mirror on the wall, who is the fairest o...",NON-P,Snow White,queen,1937,3
3,EARLY,"famed is thy beauty, majesty. but hold, a love...",NON-P,Snow White,mirror,1937,4
4,EARLY,alas for her ! reveal her name.,NON-P,Snow White,queen,1937,5

In [11]:
import nltk

In [3]:
from pymorphy2 import MorphAnalyzer
from nltk import wordpunct_tokenize
morph = MorphAnalyzer()

In [4]:
from nltk.corpus import stopwords
stops = set(stopwords.words('english'))

In [5]:
def lemmatize(x):
    if type(x) != str:
        return ""
    text = wordpunct_tokenize(x)
    result = []
    for word in text:
        if word.isalpha():
            nf = morph.parse(word)[0].normal_form
            if nf not in stops:
                result.append(nf)
    return " ".join(result)

In [6]:
from pymystem3 import Mystem
m = Mystem()

In [7]:
def parse(x):
    result = []
    ana = nltk.pos_tag(x.split())
    for tagged_token in ana:
        result.append(tagged_token[1])
    return ' '.join(result)

In [8]:
def length(x):
    return len(x)

In [9]:
df['Length'] = (df['Text']).apply(length)
df

,Disney_Period,Text,Speaker_Status,Movie,Speaker,Year,UTTERANCE_NUMBER,Length
0,EARLY,slave in the magic mirror come from the farthe...,NON-P,Snow White,queen,1937,1,125
1,EARLY,"what wouldst thou know, my queen ?",NON-P,Snow White,mirror,1937,2,35
2,EARLY,"magic mirror on the wall, who is the fairest o...",NON-P,Snow White,queen,1937,3,58
3,EARLY,"famed is thy beauty, majesty. but hold, a love...",NON-P,Snow White,mirror,1937,4,130
4,EARLY,alas for her ! reveal her name.,NON-P,Snow White,queen,1937,5,32
...,...,...,...,...,...,...,...,...
7743,LATE,we are never closing them again.,PRINCESS,Frozen,elsa,2013,984,33
7744,LATE,form on anna's boots.,PRINCESS,Frozen,elsa,2013,985,21
7745,LATE,"what? oh, elsa, they're beautiful, but you kno...",PRINCESS,Frozen,anna,2013,986,60
7746,LATE,look out. reindeer coming through!,NON-P,Frozen,kristoff,2013,987,35
7747,LATE,that's it. glide and pivot and glide and pivot.,NON-P,Frozen,olaf,2013,988,48

In [12]:
df['Text'] = df['Text'].apply(lemmatize)
df['POS'] = df['Text'].apply(parse)
df

,Disney_Period,Text,Speaker_Status,Movie,Speaker,Year,UTTERANCE_NUMBER,Length,POS
0,EARLY,slave magic mirror come farthest space wind da...,NON-P,Snow White,queen,1937,1,125,VB JJ NN VB JJS NN NN NN JJ NN JJ NN VB JJ NN
1,EARLY,wouldst thou know queen,NON-P,Snow White,mirror,1937,2,35,NN NN VBP NN
2,EARLY,magic mirror wall fairest one,NON-P,Snow White,queen,1937,3,58,JJ NN NN VBP CD
3,EARLY,famed thy beauty majesty hold lovely maid see ...,NON-P,Snow White,mirror,1937,4,130,VBN JJ NN NN VBP RB VBN NN VBZ JJ RB JJ NN NNS...
4,EARLY,alas reveal name,NON-P,Snow White,queen,1937,5,32,NNS VBP NN
...,...,...,...,...,...,...,...,...,...
7743,LATE,never closing,PRINCESS,Frozen,elsa,2013,984,33,RB NN
7744,LATE,form anna boots,PRINCESS,Frozen,elsa,2013,985,21,NN NN NNS
7745,LATE,oh elsa beautiful know ska,PRINCESS,Frozen,anna,2013,986,60,UH JJ NN VBP NN
7746,LATE,look reindeer coming,NON-P,Frozen,kristoff,2013,987,35,NN NN VBG
7747,LATE,glide pivot glide pivot,NON-P,Frozen,olaf,2013,988,48,NN NN NN NN

In [13]:
mean = df['Length'].mean()
mean

51.59112028910687

In [23]:
words = []
pos = []
for el in df['Text']:
    words.extend(el.split())
for p in df['POS']:
    pos.extend(p.split())

In [26]:
from collections import Counter
w_counter = Counter(words) #частотный словарь для слов
p_counter = Counter(pos) #для частей речи

In [19]:
text = ' '.join(words)

In [20]:
import matplotlib.pyplot as plt
from wordcloud import Wordcloud
wordcloud = WordCloud(
    background_color = "white",
    width = 800,
    height = 800,
).generate(text)
plt.imshow(wordcloud)

ModuleNotFoundError: No module named 'wordcloud'